#Minecraft server properties
#Tue Sep 29 16:49:37 IST 2026
spawn-protection=0
max-tick-time=60000
query.port=25565
generator-settings=
sync-chunk-writes=true
allow-nether=true
force-gamemode=true
enforce-whitelist=true
gamemode=survival
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=easy
broadcast-rcon-to-ops=true
spawn-monsters=true
op-permission-level=4
pvp=false
entity-broadcast-range-percentage=100
snooper-enabled=false
level-type=default
hardcore=false
enable-status=true
enable-command-block=false
network-compression-threshold=256
max-players=1
max-world-size=29999984
resource-pack-sha1=
function-permission-level=2
rcon.port=25575
server-port=25565
server-ip=127.0.0.1
spawn-npcs=true
allow-flight=false
level-name=person-dedicated-1
view-distance=8
resource-pack=
spawn-animals=true
white-list=true
rcon.password=
generate-structures=true
online-mode=false
max-build-height=256
level-seed=20260929
use-native-transport=true
prevent-proxy-connections=false
enable-jmx-monitoring=false
motd=Person research server (local, offline)
enable-rcon=false
